### ISSUE TITLE
Two Urls image for [style.background] property

### ISSUE THREAD

**Issue by HassanChmsdn** [uiuniversal/ngu-carousel#101]
How could I assign two images for the style property, in a way if its not able to get the first image it will get the second.
**I tried something like this:** 

`[style.background]=" 'url(jobimageUrl),url(http://xxx.xxx.xx/pree/image/upload/v1518056764/xxxx1a.png)' "`
or:
`[style.background]="'url(job.imageUrl) ? url(job.imageUrl) : url('https://.xxx.xxx.xxx.php/s/xxxx7jQD7NrmZ/download')'"`

but I'm not getting the result I want, any Idea, because I'm not sure if this property accepts two values and how it works! 
@fridolin-koch @sheikalthaf @gimox

**Comment by fridolin-koch** [comment]
I this has nothing to do with this library since the functionality comes from the angular core.

However, your first approach seems right: https://stackoverflow.com/questions/37588017/fallback-background-image-if-default-doesnt-exist

If `jobImageUrl` is a variable you need to use something like this:

```
[style.background]="'url(' + jobimageUrl + '),url(http://xxx.xxx.xx/pree/image/upload/v1518056764/xxxx1a.png)' "
```
